#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Jan 26, 2026 11:41:24 AM PST  platform: Windows NT

import logging
import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path
import API

logger = logging.getLogger()
_location = os.path.dirname(__file__)

# Define root globally
root = None
_top1 = None
_top2 = None
_top3 = None

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.withdraw()  #Hide the main Tk window

    global _top1
    _top1 = tk.Toplevel(root)
    _top1.protocol("WM_DELETE_WINDOW", lambda: root.destroy())  # Close all on exit
    _w1 = SignInApp(_top1)

    root.mainloop()

def openCheckInWindow():
    global _top2
    hide_signin()
    if _top2 is None or not _top2.winfo_exists():
        _top2 = tk.Toplevel(root)
        _top2.protocol("WM_DELETE_WINDOW", lambda: root.destroy())  # Close all on exit
        _w2 = checkInApp(_top2)
    else:
        _top2.focus()

def openCheckOutWindow():
    global _top3
    hide_signin()
    if _top3 is None or not _top3.winfo_exists():
        _top3 = tk.Toplevel(root)
        _top3.protocol("WM_DELETE_WINDOW", lambda: root.destroy())  # Close all on exit
        _w3 = checkOutApp(_top3)
    else:
        _top3.focus()

def close_window(name):
    if name == "_top2" and _top2 is not None:
        _top2.destroy()
        _top2 = None
    elif name == "_top3" and _top3 is not None:
        _top3.destroy()
        _top3 = None   
def hide_signin():
    if _top1 is not None:
        _top1.destroy()

_bgcolor = '#d9d9d9'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: logger.tk.call('source',
                os.path.join(_location, 'themes', 'classic.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('classic')
    style.configure('.', font = "TkDefaultFont")
    _style_code_ran = 1

class SignInApp:
    def __init__(self, top=None):
        '''This class configures and populates the Sign In window.
           top is the Sign In window.'''
        
        top.geometry("300x400+476+202")
        top.minsize(120, 1)
        top.maxsize(1924, 981)
        top.resizable(1,  1)
        top.title("Library Sign In")
        top.configure(background="#FBF9FF")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        _style_code()
        self.TEntry1 = ttk.Entry(self.top)
        self.TEntry1.place(relx=0.3, rely=0.375, relheight=0.053, relwidth=0.393)

        self.TEntry1.configure(exportselection="0")
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="ibeam")

        self.Checkin = tk.Button(self.top)
        self.Checkin.place(relx=0.317, rely=0.55, height=36, width=107)
        self.Checkin.configure(activebackground="#9395D3")
        self.Checkin.configure(activeforeground="black")
        self.Checkin.configure(background="#B3B7EE")
        self.Checkin.configure(compound='left')
        self.Checkin.configure(disabledforeground="#a3a3a3")
        self.Checkin.configure(foreground="black")
        self.Checkin.configure(highlightbackground="#d9d9d9")
        self.Checkin.configure(highlightcolor="black")
        self.Checkin.configure(text='''Check in''')
        self.Checkin.configure(command=openCheckInWindow)

        self.test = tk.Button(self.top)
        self.test.place(relx=0.317, rely=0.45, height=36, width=107)
        self.test.configure(activebackground="#9395D3")
        self.test.configure(activeforeground="black")
        self.test.configure(background="#B3B7EE")
        self.test.configure(compound='left')
        self.test.configure(disabledforeground="#a3a3a3")
        self.test.configure(foreground="black")
        self.test.configure(highlightbackground="#d9d9d9")
        self.test.configure(highlightcolor="black")
        self.test.configure(text='''sign in test''')
        self.test.configure(
            command=lambda: (
                API.get_Full_Name_By_Employee_ID(self.TEntry1.get())
                if self.TEntry1.get().strip()
                else None
            )
        )
        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.3, rely=0.1, height=61, width=146)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#FBF9FF")
        self.Label1.configure(compound='left')
        self.Label1.configure(cursor="fleur")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Arial Black} -size 24 -weight bold")
        self.Label1.configure(foreground="black")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Sign In''')

        self.Label3 = tk.Label(self.top)
        self.Label3.place(relx=0.367, rely=0.3, height=21, width=84)
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#FBF9FF")
        self.Label3.configure(compound='left')
        self.Label3.configure(cursor="fleur")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="black")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Scan your ID''')

        self.Checkin_1 = tk.Button(self.top)
        self.Checkin_1.place(relx=0.317, rely=0.7, height=36, width=107)
        self.Checkin_1.configure(activebackground="#9395D3")
        self.Checkin_1.configure(activeforeground="black")
        self.Checkin_1.configure(background="#B3B7EE")
        self.Checkin_1.configure(compound='left')
        self.Checkin_1.configure(disabledforeground="#a3a3a3")
        self.Checkin_1.configure(foreground="black")
        self.Checkin_1.configure(highlightbackground="#d9d9d9")
        self.Checkin_1.configure(highlightcolor="black")
        self.Checkin_1.configure(text='''Check out''')
        self.Checkin_1.configure(command=openCheckOutWindow)

class checkInApp:
    def __init__(self, top=None):
        '''This class configures and populates the Check In window.
           top is the Check In containing window.'''

        top.geometry("470x320+797+225")
        top.minsize(120, 1)
        top.maxsize(1924, 981)
        top.resizable(1,  1)
        top.title("Check In")
        top.configure(background="#FBF9FF")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        ########### start #######################
        ########### end #######################

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.574, rely=0.688, height=36, width=137)
        self.Button2.configure(activebackground="#9395D3")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#B3B7EE")
        self.Button2.configure(compound='left')
        self.Button2.configure(cursor="fleur")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="black")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(text='''Check In and Exit''')
        self.Button2.configure(command=lambda: root.destroy())

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.064, rely=0.694, height=36, width=127)
        self.Button1.configure(activebackground="#9395D3")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#B3B7EE")
        self.Button1.configure(compound='left')
        self.Button1.configure(cursor="fleur")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="black")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(text='''Add to cart''')

        _style_code()
        self.TEntry1_1 = ttk.Entry(self.top)
        self.TEntry1_1.place(relx=0.085, rely=0.472, relheight=0.059
                , relwidth=0.251)
        self.TEntry1_1.configure(exportselection="0")
        self.TEntry1_1.configure(state='readonly')
        self.TEntry1_1.configure(cursor="ibeam")

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.085, rely=0.406, height=19, width=74)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#FBF9FF")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="black")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Book Name''')

        self.Label4 = tk.Label(self.top)
        self.Label4.place(relx=0.085, rely=0.281, height=21, width=114)
        self.Label4.configure(activebackground="#d9d9d9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#FBF9FF")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="black")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Scan the next book''')

        self.Scrolledlistbox1 = ScrolledListBox(self.top)
        self.Scrolledlistbox1.place(relx=0.511, rely=0.25, relheight=0.297
                , relwidth=0.428)
        self.Scrolledlistbox1.configure(background="white")
        self.Scrolledlistbox1.configure(cursor="xterm")
        self.Scrolledlistbox1.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox1.configure(exportselection="0")
        self.Scrolledlistbox1.configure(font="TkFixedFont")
        self.Scrolledlistbox1.configure(foreground="black")
        self.Scrolledlistbox1.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox1.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox1.configure(selectbackground="#d9d9d9")
        self.Scrolledlistbox1.configure(selectforeground="black")

        self.Label1_1 = tk.Label(self.top)
        self.Label1_1.place(relx=0.064, rely=0.031, height=61, width=186)
        self.Label1_1.configure(activebackground="#d9d9d9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(anchor='w')
        self.Label1_1.configure(background="#FBF9FF")
        self.Label1_1.configure(compound='left')
        self.Label1_1.configure(cursor="fleur")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Arial Black} -size 24 -weight bold")
        self.Label1_1.configure(foreground="black")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Check In''')

class checkOutApp:
    def __init__(self, top=None):
        '''This class configures and populates the Checkout window.
           top is the Checkout containing window.'''

        top.geometry("470x320+794+579")
        top.minsize(120, 1)
        top.maxsize(1924, 981)
        top.resizable(1,  1)
        top.title("Check Out")
        top.configure(background="#FBF9FF")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Button1_1 = tk.Button(self.top)
        self.Button1_1.place(relx=0.064, rely=0.694, height=36, width=127)
        self.Button1_1.configure(activebackground="#9395D3")
        self.Button1_1.configure(activeforeground="black")
        self.Button1_1.configure(background="#B3B7EE")
        self.Button1_1.configure(compound='left')
        self.Button1_1.configure(cursor="fleur")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(foreground="black")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(text='''Add to cart''')

        _style_code()
        self.TEntry1_1_1 = ttk.Entry(self.top)
        self.TEntry1_1_1.place(relx=0.085, rely=0.472, relheight=0.059
                , relwidth=0.251)
        self.TEntry1_1_1.configure(exportselection="0")
        self.TEntry1_1_1.configure(state='readonly')
        self.TEntry1_1_1.configure(cursor="ibeam")

        self.Label2_1 = tk.Label(self.top)
        self.Label2_1.place(relx=0.085, rely=0.406, height=19, width=74)
        self.Label2_1.configure(activebackground="#d9d9d9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(anchor='w')
        self.Label2_1.configure(background="#FBF9FF")
        self.Label2_1.configure(compound='left')
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(foreground="black")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Book Name''')

        self.Label4_1 = tk.Label(self.top)
        self.Label4_1.place(relx=0.085, rely=0.281, height=21, width=114)
        self.Label4_1.configure(activebackground="#d9d9d9")
        self.Label4_1.configure(activeforeground="black")
        self.Label4_1.configure(anchor='w')
        self.Label4_1.configure(background="#FBF9FF")
        self.Label4_1.configure(compound='left')
        self.Label4_1.configure(disabledforeground="#a3a3a3")
        self.Label4_1.configure(foreground="black")
        self.Label4_1.configure(highlightbackground="#d9d9d9")
        self.Label4_1.configure(highlightcolor="black")
        self.Label4_1.configure(text='''Scan the next book''')

        self.Scrolledlistbox1_1 = ScrolledListBox(self.top)
        self.Scrolledlistbox1_1.place(relx=0.511, rely=0.25, relheight=0.297
                , relwidth=0.428)
        self.Scrolledlistbox1_1.configure(background="white")
        self.Scrolledlistbox1_1.configure(cursor="xterm")
        self.Scrolledlistbox1_1.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox1_1.configure(exportselection="0")
        self.Scrolledlistbox1_1.configure(font="TkFixedFont")
        self.Scrolledlistbox1_1.configure(foreground="black")
        self.Scrolledlistbox1_1.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox1_1.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox1_1.configure(selectbackground="#d9d9d9")
        self.Scrolledlistbox1_1.configure(selectforeground="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        ########### start #######################
        ########### end #######################

        self.Label1_1_1 = tk.Label(self.top)
        self.Label1_1_1.place(relx=0.064, rely=0.031, height=61, width=186)
        self.Label1_1_1.configure(activebackground="#d9d9d9")
        self.Label1_1_1.configure(activeforeground="black")
        self.Label1_1_1.configure(anchor='w')
        self.Label1_1_1.configure(background="#FBF9FF")
        self.Label1_1_1.configure(compound='left')
        self.Label1_1_1.configure(cursor="fleur")
        self.Label1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1_1.configure(font="-family {Arial Black} -size 24 -weight bold")
        self.Label1_1_1.configure(foreground="black")
        self.Label1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1_1.configure(highlightcolor="black")
        self.Label1_1_1.configure(text='''Check Out''')

        self.Button2_1 = tk.Button(self.top)
        self.Button2_1.place(relx=0.574, rely=0.688, height=36, width=137)
        self.Button2_1.configure(activebackground="#9395D3")
        self.Button2_1.configure(activeforeground="black")
        self.Button2_1.configure(background="#B3B7EE")
        self.Button2_1.configure(compound='left')
        self.Button2_1.configure(cursor="fleur")
        self.Button2_1.configure(disabledforeground="#a3a3a3")
        self.Button2_1.configure(foreground="black")
        self.Button2_1.configure(highlightbackground="#d9d9d9")
        self.Button2_1.configure(highlightcolor="black")
        self.Button2_1.configure(text='''Check Out and Exit''')
        self.Button2_1.configure(command=lambda: root.destroy())

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, tk.Listbox):
    '''A standard Tkinter Listbox widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)
    def size_(self):
        sz = tk.Listbox.size(self)
        return sz

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')
def start_up():
    main()

if __name__ == '__main__':
    main()




