#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Jan 27, 2026 03:50:44 PM PST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import AdminApp_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return
    AdminApp_support.root.tk.eval('set ::xframe #d9d9d9')
    AdminApp_support.root.tk.eval('set ::xfore #000000')
    AdminApp_support.root.tk.eval('set ::ana2color beige')
    AdminApp_support.root.tk.eval('set ::_tabfg1 black')
    AdminApp_support.root.tk.eval('set ::_tabfg2 white')
    AdminApp_support.root.tk.eval('set ::_tabbg1 #d9d9d9')
    AdminApp_support.root.tk.eval('set ::_tabbg2 gray40')
    AdminApp_support.root.tk.eval('set ::_bgmode light')        
    try: AdminApp_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'page-legacy.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('page-legacy')
    style.configure('.', font = "TkDefaultFont")
    AdminApp_support.root.tk_setPalette(
            foreground = '#000000',
            background = '#d9d9d9',
            activeForeground = 'black',
            activeBackground = '#d9d9d9',
            selectForeground = 'black',
            selectBackground =  '#d9d9d9')
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x472+431+121")
        top.minsize(120, 1)
        top.maxsize(1924, 981)
        top.resizable(0,  0)
        top.title("Add Assets")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        _style_code()
        self.TSeparator1 = ttk.Separator(self.top)
        self.TSeparator1.place(x=190, y=-10, height=490)
        self.TSeparator1.configure(orient="vertical")

        self.Button2 = tk.Button(self.top)
        self.Button2.place(x=10, y=420, height=36, width=167)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(compound='left')
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="#000000")
        self.Button2.configure(text='''Commit to Server''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        ########### start #######################
        ########### end #######################

        self.TSeparator2 = ttk.Separator(self.top)
        self.TSeparator2.place(x=0, y=40, width=600)

        self.TLabel1 = ttk.Label(self.top)
        self.TLabel1.place(x=10, y=100, height=19, width=126)
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief="flat")
        self.TLabel1.configure(text='''*.csv files only''')
        self.TLabel1.configure(compound='left')

        self.Button1 = tk.Button(self.top)
        self.Button1.place(x=10, y=50, height=36, width=167)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Choose a file''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(x=10, y=10, height=21, width=174)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 18")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Add new Assets''')

        self.Scrolledlistbox1 = ScrolledListBox(self.top)
        self.Scrolledlistbox1.place(x=200, y=50, height=415, width=391)
        self.Scrolledlistbox1.configure(background="white")
        self.Scrolledlistbox1.configure(cursor="xterm")
        self.Scrolledlistbox1.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox1.configure(exportselection="0")
        self.Scrolledlistbox1.configure(font="TkFixedFont")
        self.Scrolledlistbox1.configure(foreground="#000000")
        self.Scrolledlistbox1.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox1.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox1.configure(selectbackground="#d9d9d9")
        self.Scrolledlistbox1.configure(selectforeground="black")

class Toplevel1_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x472+694+444")
        top.minsize(120, 1)
        top.maxsize(1924, 981)
        top.resizable(0,  0)
        top.title("Add Users")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        _style_code()
        self.TSeparator1_1 = ttk.Separator(self.top)
        self.TSeparator1_1.place(x=190, y=-10, height=490)
        self.TSeparator1_1.configure(orient="vertical")

        self.Button2_1 = tk.Button(self.top)
        self.Button2_1.place(x=10, y=420, height=36, width=167)
        self.Button2_1.configure(activebackground="#d9d9d9")
        self.Button2_1.configure(activeforeground="black")
        self.Button2_1.configure(background="#d9d9d9")
        self.Button2_1.configure(compound='left')
        self.Button2_1.configure(disabledforeground="#a3a3a3")
        self.Button2_1.configure(foreground="#000000")
        self.Button2_1.configure(highlightbackground="#d9d9d9")
        self.Button2_1.configure(highlightcolor="#000000")
        self.Button2_1.configure(text='''Commit to Server''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        ########### start #######################
        ########### end #######################

        self.TSeparator3 = ttk.Separator(self.top)
        self.TSeparator3.place(x=-10, y=40, width=620)

        self.Button1_1 = tk.Button(self.top)
        self.Button1_1.place(x=10, y=50, height=36, width=167)
        self.Button1_1.configure(activebackground="#d9d9d9")
        self.Button1_1.configure(activeforeground="black")
        self.Button1_1.configure(background="#d9d9d9")
        self.Button1_1.configure(compound='left')
        self.Button1_1.configure(cursor="fleur")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="#000000")
        self.Button1_1.configure(text='''Choose a file''')

        self.TLabel1_1 = ttk.Label(self.top)
        self.TLabel1_1.place(x=10, y=100, height=19, width=126)
        self.TLabel1_1.configure(font="TkDefaultFont")
        self.TLabel1_1.configure(relief="flat")
        self.TLabel1_1.configure(text='''*.csv files only''')
        self.TLabel1_1.configure(compound='left')
        self.TLabel1_1.configure(cursor="fleur")

        self.Scrolledlistbox1_1 = ScrolledListBox(self.top)
        self.Scrolledlistbox1_1.place(x=200, y=50, height=415, width=391)
        self.Scrolledlistbox1_1.configure(background="white")
        self.Scrolledlistbox1_1.configure(cursor="xterm")
        self.Scrolledlistbox1_1.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox1_1.configure(exportselection="0")
        self.Scrolledlistbox1_1.configure(font="TkFixedFont")
        self.Scrolledlistbox1_1.configure(foreground="#000000")
        self.Scrolledlistbox1_1.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox1_1.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox1_1.configure(selectbackground="#d9d9d9")
        self.Scrolledlistbox1_1.configure(selectforeground="black")

        self.Label1_1 = tk.Label(self.top)
        self.Label1_1.place(x=10, y=10, height=21, width=174)
        self.Label1_1.configure(activebackground="#d9d9d9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(anchor='w')
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(compound='left')
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Segoe UI} -size 18")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="#000000")
        self.Label1_1.configure(text='''Add new Users''')

class Toplevel2:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("210x170+401+627")
        top.minsize(120, 1)
        top.maxsize(1924, 981)
        top.resizable(0,  0)
        top.title("Home")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.Label2 = tk.Label(self.top)
        self.Label2.place(x=30, y=10, height=21, width=154)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(cursor="fleur")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="#000000")
        self.Label2.configure(text='''What would you like to do?''')

        self.Button1_2 = tk.Button(self.top)
        self.Button1_2.place(x=20, y=50, height=36, width=167)
        self.Button1_2.configure(activebackground="#d9d9d9")
        self.Button1_2.configure(activeforeground="black")
        self.Button1_2.configure(background="#d9d9d9")
        self.Button1_2.configure(compound='left')
        self.Button1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_2.configure(foreground="#000000")
        self.Button1_2.configure(highlightbackground="#d9d9d9")
        self.Button1_2.configure(highlightcolor="#000000")
        self.Button1_2.configure(text='''Add new assets''')

        self.Button1_2_1 = tk.Button(self.top)
        self.Button1_2_1.place(x=20, y=110, height=36, width=167)
        self.Button1_2_1.configure(activebackground="#d9d9d9")
        self.Button1_2_1.configure(activeforeground="black")
        self.Button1_2_1.configure(background="#d9d9d9")
        self.Button1_2_1.configure(compound='left')
        self.Button1_2_1.configure(cursor="fleur")
        self.Button1_2_1.configure(disabledforeground="#a3a3a3")
        self.Button1_2_1.configure(foreground="#000000")
        self.Button1_2_1.configure(highlightbackground="#d9d9d9")
        self.Button1_2_1.configure(highlightcolor="#000000")
        self.Button1_2_1.configure(text='''Add new Users''')

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, tk.Listbox):
    '''A standard Tkinter Listbox widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)
    def size_(self):
        sz = tk.Listbox.size(self)
        return sz

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')
def start_up():
    AdminApp_support.main()

if __name__ == '__main__':
    AdminApp_support.main()




