#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Jan 27, 2026 03:50:56 PM PST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import AdminApp

_debug = True # False to eliminate debug printing from callback functions.



if __name__ == '__main__':
    AdminApp.start_up()




